/** Kind registry — family-colored chips (MIT originals + optional SVG icons). */

import { kindIconHref } from './icons.js';

export const FAMILIES = {
  esri: { fill: '#0079c1', on: '#fff', label: 'Esri' },
  aws: { fill: '#ff9900', on: '#111', label: 'AWS' },
  azure: { fill: '#0078d4', on: '#fff', label: 'Azure' },
  gcp: { fill: '#1a73e8', on: '#fff', label: 'GCP' },
  oci: { fill: '#c74634', on: '#fff', label: 'OCI' },
  k8s: { fill: '#326ce5', on: '#fff', label: 'K8s' },
  nutanix: { fill: '#1a7a9c', on: '#fff', label: 'Nutanix' },
  nkp: { fill: '#0e5c75', on: '#fff', label: 'NKP' },
  ctr: { fill: '#4b5563', on: '#fff', label: 'Ctr' },
  it: { fill: '#57534e', on: '#fff', label: 'IT' },
};

const ALIASES = {
  'azure.stackhci': 'azure.hci',
  'azure.local': 'azure.hci',
  'azure.activedirectory': 'azure.entra',
  'azure.ad': 'azure.entra',
  'aws.elb': 'aws.alb',
  'aws.elbv2': 'aws.alb',
  'aws.api_gateway': 'aws.apigateway',
  'aws.api-gateway': 'aws.apigateway',
  'aws.ddb': 'aws.dynamodb',
};

/** Short monogram for chip face */
const MONO = {
  'esri.portal': 'P',
  'esri.map': 'M',
  'esri.agol': 'AG',
  'esri.gdb': 'GDB',
  'esri.feature': 'FC',
  'aws.s3': 'S3',
  'aws.ec2': 'EC2',
  'aws.lambda': 'λ',
  'aws.vpc': 'VPC',
  'aws.alb': 'ALB',
  'aws.nlb': 'NLB',
  'aws.apigateway': 'API',
  'aws.cloudfront': 'CF',
  'aws.route53': 'R53',
  'aws.rds': 'RDS',
  'aws.aurora': 'Aur',
  'aws.dynamodb': 'DDB',
  'aws.elasticache': 'Cache',
  'aws.ecs': 'ECS',
  'aws.eks': 'EKS',
  'aws.fargate': 'Farg',
  'aws.ecr': 'ECR',
  'aws.sqs': 'SQS',
  'aws.sns': 'SNS',
  'aws.iam': 'IAM',
  'aws.cloudwatch': 'CW',
  'aws.secretsmanager': 'Sec',
  'aws.cognito': 'Cog',
  'aws.waf': 'WAF',
  'aws.subnet': 'Sub',
  'aws.nat': 'NAT',
  'aws.asg': 'ASG',
  'azure.hci': 'HCI',
  'azure.arc': 'Arc',
  'azure.vm': 'VM',
  'azure.aks': 'AKS',
  'azure.storage': 'ST',
  'azure.vnet': 'VNet',
  'azure.keyvault': 'KV',
  'azure.monitor': 'Mon',
  'azure.appservice': 'App',
  'azure.functions': 'Fx',
  'azure.sql': 'SQL',
  'azure.cosmos': 'Cos',
  'azure.frontdoor': 'AFD',
  'azure.appgateway': 'AGW',
  'azure.loadbalancer': 'LB',
  'azure.entra': 'Entra',
  'azure.aad': 'Entra',
  'azure.redis': 'Redis',
  'azure.eventhubs': 'EH',
  'azure.servicebus': 'SB',
  'azure.containerapps': 'ACA',
  'azure.acr': 'ACR',
  'azure.appinsights': 'AI',
  'azure.bastion': 'Bas',
  'azure.firewall': 'FW',
  'azure.subnet': 'Sub',
  'azure.nsg': 'NSG',
  'azure.privateendpoint': 'PE',
  'azure.devops': 'ADO',
  'azure.pipelines': 'Pipe',
  'azure.dns': 'DNS',
  'azure.cdn': 'CDN',
  'azure.blob': 'Blob',
  'azure.files': 'Files',
  'azure.postgresql': 'PG',
  'azure.mysql': 'MySQL',
  'azure.vmss': 'VMSS',
  'azure.apim': 'APIM',
  'gcp.gke': 'GKE',
  'gcp.compute': 'CE',
  'oci.compute': 'C',
  'k8s.cluster': 'K8s',
  'k8s.node': 'N',
  'k8s.ns': 'NS',
  'nutanix.ahv': 'AHV',
  'nutanix.aos': 'AOS',
  'nutanix.nci': 'NCI',
  'nutanix.prism': 'PC',
  'nutanix.prismcentral': 'PC',
  'nutanix.vm': 'VM',
  'nutanix.files': 'Fil',
  'nutanix.objects': 'Obj',
  'nutanix.flow': 'Flow',
  'nkp.management': 'Mgt',
  'nkp.managed': 'WK',
  'nkp.attached': 'Att',
  'nkp.workspace': 'WS',
  'nkp.project': 'Prj',
  'nkp.konvoy': 'Kon',
  'nkp.kommander': 'Kom',
  'nkp.capi': 'CAPI',
  'nkp.flux': 'Flux',
  'nkp.prometheus': 'Prom',
  'nkp.grafana': 'Grf',
  'nkp.velero': 'Vel',
  'nkp.dex': 'Dex',
  'nkp.csi': 'CSI',
  'nkp.gatekeeper': 'Gk',
  'ctr.pod': 'Pod',
  'ctr.deployment': 'Dep',
  'ctr.statefulset': 'STS',
  'ctr.service': 'Svc',
  'ctr.ingress': 'Ing',
  'ctr.container': 'Ctr',
  'ctr.registry': 'Reg',
  'ctr.helm': 'Helm',
  'esri.portal': 'P',
  'esri.map': 'M',
  'esri.agol': 'AG',
  'esri.gdb': 'GDB',
  'esri.feature': 'FC',
  'esri.scene': '3D',
  'esri.notebook': 'NB',
  'esri.server': 'Srv',
  'esri.datastore': 'DS',
  'esri.experience': 'EX',
  'esri.enterprise': 'AGE',
  'esri.manager': 'Mgr',
  'esri.identity': 'IdP',
  'esri.relational': 'RDS',
  'esri.spatiotemporal': 'ST',
  'esri.objectstore': 'OS',
  'esri.raster': 'RA',
  'esri.gp': 'GP',
  'esri.webadaptor': 'WA',
  'esri.tilecache': 'TC',
  'esri.geoevent': 'GE',
  'esri.geoanalytics': 'GA',
  'esri.image': 'Img',
  'esri.mission': 'Mis',
  'esri.knowledge': 'KG',
  'esri.workflow': 'WFM',
  'esri.hosting': 'Host',
  'esri.lb': 'LB',
  'esri.viewer': 'View',
  'esri.contributor': 'Edit',
  'esri.mobileworker': 'Field',
  'esri.creator': 'Make',
  'esri.professional': 'Pro',
  'esri.professionalplus': 'Pro+',
  'esri.nameduser': 'NU',
  'esri.spatial': 'SA',
  'esri.network': 'NA',
  'esri.analyst3d': '3DA',
  'esri.imageanalyst': 'IA',
  'esri.geostat': 'GA',
  'esri.interop': 'DI',
  'esri.publisher': 'Pub',
  'esri.insights': 'Ins',
  'esri.velocity': 'Vel',
  'it.waf': 'WAF',
  'it.step': '•',
  'it.person': 'P',
  'it.db': 'DB',
  'it.api': 'API',
  'it.queue': 'Q',
  'it.cache': 'Cache',
  'it.lb': 'LB',
};

export function normalizeKind(kind) {
  if (!kind) return null;
  const k = String(kind).trim().toLowerCase();
  return ALIASES[k] || k;
}

export function familyOf(kind) {
  const k = normalizeKind(kind);
  if (!k) return null;
  const prefix = k.split('.')[0];
  return FAMILIES[prefix] || FAMILIES.it;
}

/** Official-ish AWS Architecture category colors (icon sits on this square). */
const KIND_FILL = {
  'aws.ec2': '#ED7100',
  'aws.lambda': '#ED7100',
  'aws.ecs': '#ED7100',
  'aws.eks': '#ED7100',
  'aws.fargate': '#ED7100',
  'aws.asg': '#ED7100',
  'aws.ecr': '#ED7100',
  'aws.s3': '#3F8624',
  'aws.rds': '#C925D1',
  'aws.aurora': '#C925D1',
  'aws.dynamodb': '#C925D1',
  'aws.elasticache': '#C925D1',
  'aws.vpc': '#8C4FFF',
  'aws.alb': '#8C4FFF',
  'aws.nlb': '#8C4FFF',
  'aws.cloudfront': '#8C4FFF',
  'aws.route53': '#8C4FFF',
  'aws.apigateway': '#8C4FFF',
  'aws.nat': '#8C4FFF',
  'aws.subnet': '#8C4FFF',
  'aws.waf': '#DD344C',
  'aws.iam': '#DD344C',
  'aws.cognito': '#DD344C',
  'aws.secretsmanager': '#DD344C',
  'aws.cloudwatch': '#E7157B',
  'aws.sqs': '#E7157B',
  'aws.sns': '#E7157B',
};

export function chipLabel(kind) {
  const k = normalizeKind(kind);
  if (!k) return '?';
  if (MONO[k]) return MONO[k];
  const leaf = k.split('.').pop() || '?';
  return leaf.slice(0, 3).toUpperCase();
}

export function kindMeta(kind) {
  const id = normalizeKind(kind);
  const family = familyOf(id) || FAMILIES.it;
  const fill = (id && KIND_FILL[id]) || family.fill;
  // White strokes on category squares; dark ink only on light fills (e.g. AWS orange monogram legacy)
  const on = KIND_FILL[id] ? '#fff' : family.on;
  return {
    id,
    family: id ? id.split('.')[0] : 'it',
    fill,
    on,
    mono: chipLabel(id),
    icon: kindIconHref(id),
  };
}
